### ISSUE TITLE
Failed to spawn: undefined symbol: main

### ISSUE THREAD

**Issue by VendorAttestation** [zer0def/undetected-frida#3]
Failed to spawn: undefined symbol: main

**Comment by TheVisual** [comment]
might be related to https://github.com/Ylarod/Florida/issues/6#issue-2319377100

**Comment by zer0def** [comment]
That's actually my bad, as I have looped back `0005-symbol_frida_agent_main.patch` into the build, since it was previously marked as `.tmpbak`, implying that may have been a transitive issue.

That said, sounds like one more thing to look into and fixup to avoid having easily greppable symbols in binaries.

Thanks for bringing this up nonetheless, queued up a fresh build that should become available at ~the next full hour.
