### ISSUE TITLE
Stuck Spawning `app`...

### ISSUE THREAD

**Issue by VendorAttestation** [zer0def/undetected-frida#4]
Stuck Spawning `app`... app never spawns Failed to spawn: timeout was reached

**Comment by zer0def** [comment]
This looks like a variation of Exo1i/MagiskHluda#4. Some mitigations can be found [here](https://github.com/frida/frida/issues/1788#issuecomment-2100619656). MoonBirdLin's packaging attempts to [incorporate them](https://github.com/MoonBirdLin/magisk-florida/blob/15737db04f66de4eb4099e2b0cedb9ba5447fa6f/base/common/service.sh#L20-L22). YMMV.

Given this issue applies just as inconsistently to upstream Frida and that I can't deterministically replicate it on my end, I'll have to call "not invented here", because it doesn't stem from these modifications and there's no sensible consensus on whom it applies to or how to address it, nor will I ever package a module disabling SELinux.
